In [9]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [10]:

from pyspark_data_provenance import (
    data_provenance_enabled, 
    data_provenance_session_builder,
    provenance_column_name
)

In [11]:
from pyspark.sql import SparkSession

spark = (
    # SparkSession
    # .builder
    data_provenance_session_builder()
    .appName("data-provenance-notebook")
    .getOrCreate()
)

### Create toy dataframe

In [12]:
from datetime import date
import pandas as pd

df = spark.createDataFrame([
    ("A", date(2026, 1, 15), 10.0, 90),
    ("A", date(2026, 1, 16), 10.0, 120),
    ("A", date(2026, 1, 17), 5.0, 300),
    ("B", date(2026, 1, 15), 100.0, 20),
    ("B", date(2026, 1, 16), 100.0, 30),
    ("B", date(2026, 1, 17), 80.0, 60),
], ["product", "date", "price", "sales"]
)
df.printSchema()

df.toPandas()

root
 |-- product: string (nullable = true)
 |-- date: date (nullable = true)
 |-- price: double (nullable = true)
 |-- sales: long (nullable = true)

  product        date  price  sales
0       A  2026-01-15   10.0     90
1       A  2026-01-16   10.0    120
2       A  2026-01-17    5.0    300
3       B  2026-01-15  100.0     20
4       B  2026-01-16  100.0     30
5       B  2026-01-17   80.0     60

### Test with pyspark syntax

In [13]:
df2 = df.select("product")

df2.toPandas()

  product
0       A
1       A
2       A
3       B
4       B
5       B

In [14]:
with data_provenance_enabled(spark, df) as df_with_provenance:
    res = df_with_provenance.toPandas()

res

  product        date  price  sales                       _provenance_tag
0       A  2026-01-15   10.0     90  7124bc83-db17-4a5c-a9f3-602e6256a3de
1       A  2026-01-16   10.0    120  9f007028-aca9-4df9-8e84-87823c978925
2       A  2026-01-17    5.0    300  c30020f8-c203-48e7-a6bc-137284a06051
3       B  2026-01-15  100.0     20  82ea0c62-2199-43f6-8a97-bf40e80b0df0
4       B  2026-01-16  100.0     30  8c4cf578-ce9a-4c44-ad4d-c9c73327dfc4
5       B  2026-01-17   80.0     60  9be49ac4-9ff9-4c1f-8c94-f07dc7855a4a

### Test with SQL syntax

In [15]:
df.createOrReplaceTempView("sales")

spark.sql("select * from sales").toPandas()

  product        date  price  sales
0       A  2026-01-15   10.0     90
1       A  2026-01-16   10.0    120
2       A  2026-01-17    5.0    300
3       B  2026-01-15  100.0     20
4       B  2026-01-16  100.0     30
5       B  2026-01-17   80.0     60

In [16]:
df.createOrReplaceTempView("sales")

with data_provenance_enabled(spark, "sales") as view_with_provenance:
    res = spark.table(view_with_provenance).toPandas()

res

  product        date  price  sales                       _provenance_tag
0       A  2026-01-15   10.0     90  bf087bc5-91a0-402d-b200-629a0f706e8d
1       A  2026-01-16   10.0    120  dcc2eb9c-e773-497a-866a-09ec371efc9f
2       A  2026-01-17    5.0    300  0b932015-8927-4fe1-8435-11541affcf54
3       B  2026-01-15  100.0     20  e6a41328-2cca-419f-895d-be7c8b2ea8fd
4       B  2026-01-16  100.0     30  40d28dee-b69a-4c88-95f1-06609e47bc19
5       B  2026-01-17   80.0     60  9f2bb06a-f9bd-4699-abdb-2b3a237e06f9

### Test with multiple dataframes/views and with custom name for provenance column

In [17]:
spark.conf.set("spark.provenance.columnName", "toto")
print(provenance_column_name(spark))

with data_provenance_enabled(spark, df, "sales", df2) as (df_with_provenance, view_with_provenance, df2_with_provenance):
    res = df_with_provenance.toPandas()
    res2 = spark.table(view_with_provenance).toPandas()
    res3 = df2_with_provenance.toPandas()

print(res)
print(res2)
res3

toto
  product        date  price  sales                                  toto
0       A  2026-01-15   10.0     90  cf8e1108-55be-431e-beea-5c8860974d55
1       A  2026-01-16   10.0    120  2a618d58-1066-4e04-97a2-86564dff6622
2       A  2026-01-17    5.0    300  988abf68-703a-48b9-9a46-d07f8dcbef8c
3       B  2026-01-15  100.0     20  f35ae4f9-c5c3-4744-9b87-16995b78dfd1
4       B  2026-01-16  100.0     30  80465a59-8575-40c4-8490-afa081775205
5       B  2026-01-17   80.0     60  61594bde-69c7-4359-9e4d-e6392d3ff006
  product        date  price  sales                                  toto
0       A  2026-01-15   10.0     90  e4eeeb06-d466-454c-87e3-4181f26178fc
1       A  2026-01-16   10.0    120  8e0c26af-2f8e-46a1-85d4-a4093bf9ae7d
2       A  2026-01-17    5.0    300  3c36be3f-7cbf-4672-bc59-9f9ca60a7ea8
3       B  2026-01-15  100.0     20  f4d79cb2-9a72-45cb-a694-e467d15f484a
4       B  2026-01-16  100.0     30  ae007959-2cbb-441a-8d4c-7962042ebfa7
5       B  2026-01-17   80.0     60  807243ff-40d6-46ae-ac20-89245eaa597a

  product                                  toto
0       A  4c085339-8fb5-4c4a-9705-088cbc2855dd
1       A  7f884db5-ee75-408c-83dc-c3f9aca0b565
2       A  f43a528f-ebf4-4a16-afbe-e9247d000fe7
3       B  b1089406-70e9-4ba8-95fa-f3fac80de916
4       B  ab89ea1c-b34c-4ba1-a155-678de0d2af3c
5       B  4eeac539-0f2a-475b-916e-b3a0593238ba